/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Skylar (https://sketchfab.com/itsmeskylar)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/barrett-mrad-sniper-rifle-80fd840273f64af59f44edb07df07bbf
Title: Barrett MRAD Sniper Rifle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Barrett(props) {
  const { nodes, materials } = useGLTF('/models/barrett/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 1.7]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Magazine_low} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Stock_low_001} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Stock_cheek_adjustment_low} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Stock_cheek_screw_low} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Stock_pad_adjustment_low} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Lower_reciever_low_001} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Upper_reciever_low} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Barrel_low} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.Bolt_adapter_low} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.Bolt_low} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.Grip_low} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.safety_low} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.magazine_release_low} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.Trigger_low} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/barrett/scene.gltf')
